/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Stats */
        get: operations["get_dashboard_stats_api_v1_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        /** Create Lead */
        post: operations["create_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Leads Csv */
        get: operations["export_leads_csv_api_v1_leads_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_api_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        /** Delete Lead */
        delete: operations["delete_lead_api_v1_leads__lead_id__delete"];
        options?: never;
        head?: never;
        /** Update Lead */
        patch: operations["update_lead_api_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Existing Lead */
        post: operations["analyze_existing_lead_api_v1_leads__lead_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{lead_id}/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notify Existing Lead */
        post: operations["notify_existing_lead_api_v1_leads__lead_id__notify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_meta_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_settings_patch"];
        trace?: never;
    };
    "/api/v1/settings/test-telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Telegram */
        post: operations["test_telegram_api_v1_settings_test_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/testing/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Database
         * @description Wipe all leads and settings, then reseed deterministic demo data.
         *
         *     Only available when ENVIRONMENT=test (set by the Playwright webServer),
         *     so this can never be reached against a real deployment.
         */
        post: operations["reset_database_api_v1_testing_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisStatus
         * @enum {string}
         */
        AnalysisStatus: "not_requested" | "pending" | "completed" | "failed";
        /** DashboardStats */
        DashboardStats: {
            /** By Priority */
            by_priority: components["schemas"]["PriorityBucket"][];
            /** Conversion Rate */
            conversion_rate: number;
            /** High Priority */
            high_priority: number;
            /** New */
            new: number;
            /** Recent Leads */
            recent_leads: components["schemas"]["LeadRead"][];
            /** Total */
            total: number;
            /** Urgent */
            urgent: number;
            /** Won */
            won: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Name */
            app_name: string;
            /** App Version */
            app_version: string;
            /** Status */
            status: string;
        };
        /**
         * LeadCreate
         * @example {
         *       "budget_text": "around $20k",
         *       "company": "Acme Web Co",
         *       "deadline_text_input": "within 2 months",
         *       "description": "We need a marketing website redesign with a CMS and blog.",
         *       "email": "alice@example.com",
         *       "name": "Alice Anderson",
         *       "source": "website"
         *     }
         */
        LeadCreate: {
            /** Budget Text */
            budget_text?: string | null;
            /** Company */
            company?: string | null;
            /** Deadline Text Input */
            deadline_text_input?: string | null;
            /** Description */
            description: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** @default manual */
            source: components["schemas"]["LeadSource"];
        };
        /** LeadListResponse */
        LeadListResponse: {
            /** Items */
            items: components["schemas"]["LeadRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * LeadPriority
         * @enum {string}
         */
        LeadPriority: "low" | "medium" | "high" | "urgent";
        /** LeadRead */
        LeadRead: {
            /** Ai Model */
            ai_model: string | null;
            /** Ai Summary */
            ai_summary: string | null;
            /** Analysis Error */
            analysis_error: string | null;
            /** Analysis Reasons */
            analysis_reasons: string[];
            analysis_status: components["schemas"]["AnalysisStatus"];
            /** Budget Max */
            budget_max: number | null;
            /** Budget Min */
            budget_min: number | null;
            /** Budget Text */
            budget_text: string | null;
            /** Category */
            category: string | null;
            /** Company */
            company: string | null;
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string | null;
            /** Deadline Text */
            deadline_text: string | null;
            /** Deadline Text Input */
            deadline_text_input: string | null;
            /** Description */
            description: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Last Notified At */
            last_notified_at: string | null;
            /** Name */
            name: string;
            /** Notification Error */
            notification_error: string | null;
            notification_status: components["schemas"]["NotificationStatus"];
            priority: components["schemas"]["LeadPriority"] | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Recommended Action */
            recommended_action: string | null;
            source: components["schemas"]["LeadSource"];
            status: components["schemas"]["LeadStatus"];
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LeadSortField
         * @enum {string}
         */
        LeadSortField: "created_at" | "updated_at" | "name" | "priority" | "status";
        /**
         * LeadSource
         * @enum {string}
         */
        LeadSource: "website" | "email" | "telegram" | "referral" | "manual" | "other";
        /**
         * LeadStatus
         * @enum {string}
         */
        LeadStatus: "new" | "contacted" | "qualified" | "won" | "lost";
        /**
         * LeadUpdate
         * @description Partial update; only provided fields are changed.
         * @example {
         *       "priority": "high",
         *       "status": "contacted"
         *     }
         */
        LeadUpdate: {
            /** Budget Text */
            budget_text?: string | null;
            /** Category */
            category?: string | null;
            /** Company */
            company?: string | null;
            /** Deadline Text Input */
            deadline_text_input?: string | null;
            /** Description */
            description?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            priority?: components["schemas"]["LeadPriority"] | null;
            source?: components["schemas"]["LeadSource"] | null;
            status?: components["schemas"]["LeadStatus"] | null;
        };
        /** MetaConfigResponse */
        MetaConfigResponse: {
            /** Ai Provider */
            ai_provider: string;
            /** App Name */
            app_name: string;
            /** App Version */
            app_version: string;
            /** Environment */
            environment: string;
            /** Telegram Provider */
            telegram_provider: string;
        };
        /**
         * NotificationStatus
         * @enum {string}
         */
        NotificationStatus: "not_required" | "pending" | "sent" | "failed";
        /** PriorityBucket */
        PriorityBucket: {
            /** Count */
            count: number;
            /** Priority */
            priority: string;
        };
        /**
         * SettingsRead
         * @description Public settings view. Never includes the Telegram bot token.
         */
        SettingsRead: {
            /** Company Name */
            company_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            notify_min_priority: components["schemas"]["LeadPriority"];
            /** Telegram Chat Id */
            telegram_chat_id: string | null;
            /** Telegram Enabled */
            telegram_enabled: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Company Name */
            company_name?: string | null;
            notify_min_priority?: components["schemas"]["LeadPriority"] | null;
            /** Telegram Chat Id */
            telegram_chat_id?: string | null;
            /** Telegram Enabled */
            telegram_enabled?: boolean | null;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** TestTelegramRequest */
        TestTelegramRequest: {
            /** Chat Id */
            chat_id?: string | null;
        };
        /** TestTelegramResponse */
        TestTelegramResponse: {
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_stats_api_v1_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: components["schemas"]["LeadStatus"] | null;
                /** @description Filter by priority; 'none' isolates unclassified leads. */
                priority?: components["schemas"]["LeadPriority"] | "none" | null;
                source?: components["schemas"]["LeadSource"] | null;
                sort_by?: components["schemas"]["LeadSortField"];
                sort_order?: components["schemas"]["SortOrder"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_leads_post: {
        parameters: {
            query?: {
                /** @description Run AI analysis after saving. AI failure still returns 201. */
                analyze?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_leads_csv_api_v1_leads_export_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: components["schemas"]["LeadStatus"] | null;
                /** @description Filter by priority; 'none' isolates unclassified leads. */
                priority?: components["schemas"]["LeadPriority"] | "none" | null;
                source?: components["schemas"]["LeadSource"] | null;
                sort_by?: components["schemas"]["LeadSortField"];
                sort_order?: components["schemas"]["SortOrder"];
                /** @description Prefix a UTF-8 BOM so Excel detects the encoding. */
                bom?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_api_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lead_api_v1_leads__lead_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_api_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_existing_lead_api_v1_leads__lead_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notify_existing_lead_api_v1_leads__lead_id__notify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_v1_meta_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaConfigResponse"];
                };
            };
        };
    };
    read_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    update_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_telegram_api_v1_settings_test_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestTelegramRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestTelegramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_database_api_v1_testing_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
