import type { components } from './schema'

export type LeadPriority = components['schemas']['LeadPriority']
export type LeadStatus = components['schemas']['LeadStatus']
export type AnalysisStatus = components['schemas']['AnalysisStatus']
export type NotificationStatus = components['schemas']['NotificationStatus']
export type LeadSource = components['schemas']['LeadSource']
export type LeadSortField = components['schemas']['LeadSortField']
export type SortOrder = components['schemas']['SortOrder']
export type LeadRead = components['schemas']['LeadRead']
export type LeadCreate = components['schemas']['LeadCreate']
export type LeadUpdate = components['schemas']['LeadUpdate']
export type LeadListResponse = components['schemas']['LeadListResponse']
export type DashboardStats = components['schemas']['DashboardStats']
export type PriorityBucket = components['schemas']['PriorityBucket']
export type SettingsRead = components['schemas']['SettingsRead']
export type SettingsUpdate = components['schemas']['SettingsUpdate']
export type TestTelegramRequest = components['schemas']['TestTelegramRequest']
export type TestTelegramResponse = components['schemas']['TestTelegramResponse']
export type MetaConfigResponse = components['schemas']['MetaConfigResponse']
