"""initial schema

Revision ID: c7a995c32953
Revises:
Create Date: 2026-07-12 01:26:58.880344

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7a995c32953"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=160), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("telegram_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "notify_min_priority",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", "URGENT", name="leadpriority", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_app_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("company", sa.String(length=160), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "WEBSITE",
                "EMAIL",
                "TELEGRAM",
                "REFERRAL",
                "MANUAL",
                "OTHER",
                name="leadsource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("budget_text", sa.String(length=160), nullable=True),
        sa.Column("deadline_text_input", sa.String(length=160), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONTACTED",
                "QUALIFIED",
                "WON",
                "LOST",
                name="leadstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", "URGENT", name="leadpriority", native_enum=False, length=20
            ),
            nullable=True,
        ),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("ai_summary", sa.String(length=500), nullable=True),
        sa.Column("budget_min", sa.Integer(), nullable=True),
        sa.Column("budget_max", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("deadline_text", sa.String(length=160), nullable=True),
        sa.Column("recommended_action", sa.String(length=300), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("analysis_reasons", sa.JSON(), nullable=False),
        sa.Column(
            "analysis_status",
            sa.Enum(
                "NOT_REQUESTED",
                "PENDING",
                "COMPLETED",
                "FAILED",
                name="analysisstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("analysis_error", sa.String(length=500), nullable=True),
        sa.Column("ai_model", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column(
            "notification_status",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "SENT",
                "FAILED",
                name="notificationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notification_error", sa.String(length=500), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "budget_max IS NULL OR budget_max >= 0", name="ck_leads_budget_max_nonneg"
        ),
        sa.CheckConstraint(
            "budget_min IS NULL OR budget_min >= 0", name="ck_leads_budget_min_nonneg"
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_leads_confidence_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index("ix_leads_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_leads_email", ["email"], unique=False)
        batch_op.create_index("ix_leads_priority", ["priority"], unique=False)
        batch_op.create_index("ix_leads_status", ["status"], unique=False)
        batch_op.create_index("ix_leads_status_priority", ["status", "priority"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index("ix_leads_status_priority")
        batch_op.drop_index("ix_leads_status")
        batch_op.drop_index("ix_leads_priority")
        batch_op.drop_index("ix_leads_email")
        batch_op.drop_index("ix_leads_created_at")

    op.drop_table("leads")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
